baseURL = 'https://blog.208128.xyz/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„ Hugo åšå®¢'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ ğŸ‘‹", Content = "è¿™æ˜¯æˆ‘çš„ Hugo åšå®¢ã€‚" }
  defaultTheme = "auto"

[outputs]
  home = ["HTML"]
  section = ["HTML", "JSON"]

[menu]
  [[menu.main]]
    identifier = "åˆ‘æ³•"
    name = "åˆ‘æ³•"
    url = "/categories/åˆ‘æ³•/"
    weight = 10

  [[menu.main]]
    identifier = "æ°‘æ³•"
    name = "æ°‘æ³•"
    url = "/categories/æ°‘æ³•/"
    weight = 20

  [[menu.main]]
    identifier = "è¡Œæ”¿æ³•"
    name = "è¡Œæ”¿æ³•"
    url = "/categories/è¡Œæ”¿æ³•/"
    weight = 30

  [[menu.main]]
    identifier = "å•†ç»æ³•"
    name = "å•†ç»æ³•"
    url = "/categories/å•†ç»æ³•/"
    weight = 40

  [[menu.main]]
    identifier = "æ°‘å•†æ³•"
    name = "æ°‘å•†æ³•"
    url = "/categories/æ°‘å•†æ³•/"
    weight = 50

  [[menu.main]]
    identifier = "åˆ‘è¯‰"
    name = "åˆ‘è¯‰"
    url = "/categories/åˆ‘è¯‰/"
    weight = 60

  [[menu.main]]
    identifier = "ç†è®ºæ³•"
    name = "ç†è®ºæ³•"
    url = "/categories/ç†è®ºæ³•/"
    weight = 70

  [[menu.main]]
    identifier = "ä¸‰å›½æ³•"
    name = "ä¸‰å›½æ³•"
    url = "/categories/ä¸‰å›½æ³•/"
    weight = 80
