baseURL = 'https://208128.xyz/'
languageCode = 'zh-cn'
title = 'æˆ‘çš„ Hugo åšå®¢'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ ğŸ‘‹", Content = "è¿™æ˜¯æˆ‘çš„ Hugo åšå®¢ã€‚" }

[menu]
  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 10
